# Generated by Django 3.1.7 on 2021-07-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bids_modifiedby', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='Category',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_modifiedby', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Category',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments_modifiedby', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings_modifiedby', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
