# Generated by Django 3.1.7 on 2021-07-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210723_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='last_bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
