# Generated by Django 3.1.7 on 2021-07-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210724_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='last_bid_price',
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments_listing', to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='listings',
            name='last_high_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bids_listing', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='watchlist_listing', to='auctions.listings'),
        ),
    ]
