# Generated by Django 3.1.7 on 2021-07-30 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210730_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings_category', to='auctions.Category'),
        ),
    ]
