# Generated by Django 3.1.7 on 2021-08-01 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210801_1616'),
    ]

    operations = [
        migrations.RenameField(
            'listing',
            'Category',
            'category'
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_high_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_current_high_bid', to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
